### PR TITLE
Remove matchfunding

### PR DESCRIPTION
**Pull request by sauloperez**
The matchfunding was long over so we should have meaningful call to actions and communication.

## Missing

- [x] Fix tabs and titles alignment in portrait
- [x] Space out the three principles when in portrait
- [x] Remove consumers block from features
- [x] Replace features hero image
- [x] Translations
- [x] Link to form

### CODE REVIEW

**Comment by sauloperez** [comment]
features
index

**Comment by sseerrggii** [comment]
:+1: 

We should add subscribe to newsletter link

**Comment by sauloperez** [comment]
I'll what I can do @sseerrggii. Keep in mind that our call to action is to become a member.

**Comment by sauloperez** [comment]
we should consider highlighting more features like order confirmations/cancelations, autoclosing of order cycle, listing orders, etc.

**Comment by sauloperez** [comment]
This is it

screencapture-127-0-0-1-4000-index-html-2018-07-26-17_53_47
screencapture-127-0-0-1-4000-features-html-2018-07-26-17_54_07

**Pull request merged**
